# Generated by Django 3.1.7 on 2021-03-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210315_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.job'),
        ),
    ]
