# Generated by Django 3.1.7 on 2021-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210316_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(null=True, upload_to='notes/'),
        ),
    ]
