# Generated by Django 3.1.7 on 2021-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Closed', 'Closed')], default='New', max_length=50),
        ),
    ]
