# Generated by Django 3.1.7 on 2021-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210317_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hardware',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Printer', 'Printer'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='issue',
            field=models.CharField(choices=[('Not Turning on', 'Not Turning on'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='os',
            field=models.CharField(choices=[('PC', 'PC'), ('Mac', 'Mac'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
