# Generated by Django 3.1.7 on 2021-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='issue_speical',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
