# Generated by Django 3.1.7 on 2021-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_issue_speical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='issue',
            field=models.CharField(choices=[('Not turning on', 'Not Turning on'), ('Unknown', 'I dont know'), ('NoOn', 'Doesn’t turn on at all'), ('NoScreen', 'NoScreen'), ('BlurryScreen', 'BlurryScreen'), ('NotNormalStartup', 'NotNormalStartup'), ('NoInternet', 'NoInternet'), ('SlowComputer', 'SlowComputer'), ('NotMyHomePage', 'NotMyHomePage'), ('Virus', 'Virus'), ('NoEmail', 'NoEmail'), ('HackedEmail', 'HackedEmail'), ('HelpBuy', 'HelpBuy'), ('SetUpComputer', 'SetUpComputer'), ('Transfer', 'Transfer'), ('Wipe', 'Wipe')], default='Unknown', max_length=50),
        ),
    ]
