# Generated by Django 3.1.7 on 2021-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20210324_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='issue',
            field=models.CharField(choices=[('Not turning on', 'Not Turning on'), ('Unknown', 'I dont know'), ('NoOn', 'Doesn’t turn on at all'), ('NoScreen', 'Turns on but nothing on the screen'), ('BlurryScreen', 'Screen on but faint/blurry/lines/etc'), ('NotNormalStartup', 'Screen on but not normal startup'), ('NoInternet', 'Computer on but won’t connect to the internet'), ('SlowComputer', 'Slow Computer'), ('NotMyHomePage', 'Goes to strange websites'), ('Virus', 'Virus (malware) is causing problems'), ('NoEmail', 'No email or passwords are wrong'), ('HackedEmail', 'Email has been hacked'), ('HelpBuy', ' Buy new computer and setup'), ('SetUpComputer', 'Setup new computer already purchased'), ('Transfer', 'Transfer data or setup new w/ backup plan'), ('Wipe', 'Wipe old computer/remove hard drive')], default='Unknown', max_length=50),
        ),
    ]
