# Generated by Django 3.1.7 on 2021-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20210327_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
