# Generated by Django 3.1.7 on 2021-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_client_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_location',
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(choices=[('IOP', 'IOP'), ('Remote', 'Remote'), ('Vacationer', 'Vacationer')], default='Remote', max_length=50),
        ),
    ]
