# Generated by Django 3.1.7 on 2021-03-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210321_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='call_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('MidDay', 'MidDay'), ('Evening', 'Evening')], default='Morning', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(choices=[('IOP', 'IOP'), ('Sullivan', 'Sullivan'), ('Kiawah', 'Kiawah'), ('Seabrook', 'Seabrook'), ('MtPleasant', 'MtPleasant'), ('NorthCharleston', 'NorthCharleston'), ('WestAshely', 'WestAshely'), ('JamesIsland', 'JamesIsland'), ('GooseCreek', 'GooseCreek'), ('Summerville', 'Summerville'), ('Charleston', 'Charleston'), ('Remote', 'Remote'), ('Vacationer', 'Vacationer')], default='Remote', max_length=50),
        ),
    ]
