# Generated by Django 3.1.7 on 2021-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210321_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
