# Generated by Django 3.1.7 on 2021-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('start', models.JSONField(null=True)),
                ('end', models.JSONField(null=True)),
                ('attendees', models.JSONField(null=True)),
            ],
        ),
    ]
