# Generated by Django 3.1.7 on 2021-03-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlecal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='dateTime_start',
            field=models.DateField(null=True),
        ),
    ]
