# Generated by Django 3.1.7 on 2021-03-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlecal', '0002_auto_20210326_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dateTime_start',
        ),
    ]
