# Generated by Django 3.1.7 on 2021-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlecal', '0003_remove_event_datetime_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateTime_start',
            field=models.DateTimeField(null=True),
        ),
    ]
