# Generated by Django 3.1.7 on 2021-03-28 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_job_created_date'),
        ('googlecal', '0006_auto_20210327_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='jobs.job'),
        ),
    ]
